### ISSUE TITLE
Use elemon only in dev

### ISSUE THREAD

**Issue by richardtape** [mawni/elemon#3]
Hi!

This is great. Thank you for putting this out there. I'm new to electron app dev so this may be ridiculous, but please bear with me :)

`elemon` is a tool which only really makes sense to have in development mode. (i.e. it's a dev-dependency). That means `elemon` won't be available when a new package is created for an electron app. So we'd only like to `require` it whenever we're in development. The `electron-debug` package handles this by using the `electron-is-dev` package like this: https://github.com/sindresorhus/electron-debug/commit/4039271607d2c72a696a6f895406616435743d8a

Would that be something you would consider for `elemon` ?

If not, and it isn't too much to ask, would you please point me in the right direction as to how I could have `elemon` as a dev-dependency and still use it in my electron app so I can still build an app without it failing because `elemon` isn't defined. It's a surprisingly difficult thing to google, I have discovered :)

Thanks again, and thank you in advance.

**Comment by manidlou** [comment]
@richardtape you are right. `elemon` is a tool that you need it only in development. Essentially, in order to achieve what you want, I can think of 3 ways at this moment. Methods 2 and 3 require to use [electron-is-dev](https://github.com/sindresorhus/electron-is-dev).

1. Have 2 different `package.json` files. This refers to [two `package.json` structure](https://github.com/electron-userland/electron-builder/wiki/Two-package.json-Structure).
2. `elemon` uses `electron-is-dev` internally. Then, users install it like `npm i elemon --save`. This means users don't need to guard it for production. However, I don't like this because `elemon` has a dependency ([chokidar](https://github.com/paulmillr/chokidar)) and it means all these dependency modules will be bundled in your final app while you don't need them.
3. Users (like you) use `electron-is-dev` and use `elemon` like the following example. I believe this is better since `electron-is-dev` is just 2 lines of code and doesn't have any dependencies. So, it basically doesn't hurt to be included in your final app in terms of size and other stuff.

So, you can do something like this:
`npm i electron-is-dev --save`
`npm i elemon --save-dev`
```js
const {app, BrowserWindow} = require('electron')
const isDev = require('electron-is-dev')

function createWindows () {
  // ...
}

app.on('ready', () => {
  createWindows()

  if (isDev) {
    const elemon = require('elemon') // require elemon if electron is in dev
    elemon({
      app: app,
      mainFile: 'main.js',
      bws: [
        {bw: win1, res: ['win1.html', 'win1.js', 'style.css']},
        {bw: win2, res: ['win2.html', 'win2.js', 'style.css']}
      ]
    })
  }
})
```
Hopefully this helps you in your issue. Please let us know if you need further assistance.

**Comment by manidlou** [comment]
This feature is documented now. Please reopen if needed.
